### ISSUE TITLE
Index out of range when indexing class with generic constructor argument

### ISSUE THREAD

**Issue by fmorgner** [nextgis/kotlin_sphinx#1]
On the current git head, given the following code:

```kotlin
class Test(data: Map<Int, Int>)
```

invoking kotlinsphinx raises the following error:

```
Indexing kotlin file: /home/mof/Projects/uxv/hmi-android/doc/test/test.kt
Traceback (most recent call last):
  File "/home/mof/Projects/uxv/hmi-android/doc/env/bin/kotlinsphinx", line 10, in <module>
    sys.exit(main())
  File "/home/mof/Projects/uxv/hmi-android/doc/env/lib/python3.7/site-packages/kotlin_domain/generator.py", line 44, in main
    file_index = KotlinFileIndex([source_path])
  File "/home/mof/Projects/uxv/hmi-android/doc/env/lib/python3.7/site-packages/kotlin_domain/indexer.py", line 445, in __init__
    item['members'] = KotlinObjectIndex(contentPlus, 0, item['type'])
  File "/home/mof/Projects/uxv/hmi-android/doc/env/lib/python3.7/site-packages/kotlin_domain/indexer.py", line 633, in __init__
    if strip_variable[1]:
IndexError: list index out of range
```

**Comment by BishopGIS** [comment]
To create more informative documentation it's expected that you add some description to your class in following form:

```kt
/**
 * Catalog object class. This is base class for all catalog objects.
 *
 * @property name Object name
 * @property type Object type
 * @property path Object path
 * @property handle Object handle for C API
 */
```

For example see: https://github.com/nextgis/android_maplib/blob/v3/maplib/src/main/kotlin/com/nextgis/maplib/Catalog.kt#L28

And generated documentation at this [link](https://docs.nextgis.com/ngmobile_dev/kotlin_maplib/maplib/Catalog.html#constructor(name:type:path:handle:))
